version: "3.9"
services:
  ubuntu:
    container_name: system-lab 
    build:
      context: .
      dockerfile: ./containers.d/local/Dockerfile.latest
    ports:
      - 3000:3000
      - 4000:4000
      - 8005:8005
      - 8001:8000
      #- 8080:8080
    volumes:
      # - ./system-root/root:/root
      # - ./system-root/home/ubuntu:/home/ubuntu
      - ./system-root/home/ubuntu/dev:/home/ubuntu/dev
      - ./system-root/var/www:/var/www
      - ./shared:/opt/shared
    networks:
      - dev_net
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  dev_net:
    external: true
volumes:
  ubuntu-test:
